version: "3.8"
   
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
        context: ./frontend/
        dockerfile: Dockerfile
    ports:
        - 3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true